"""
Train a standalone SigLIP-based router via distillation from ContextAwareRouter labels.

Uses routing labels generated by generate_routing_labels.py to train a lightweight
router (~100M params) that can run independently of the 7B base model.

Loss: CE on hard labels + optional KL divergence on soft routing distribution.

Usage:
    python train_standalone_router.py \
        --labels routing_labels.jsonl \
        --output_dir standalone_router_checkpoint \
        --vision_model google/siglip-base-patch16-224 \
        --num_experts 6 \
        --epochs 10 \
        --lr 1e-4 \
        --batch_size 32
"""

import argparse
import json
import logging
import os
import sys
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, PROJECT_ROOT)

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


class RoutingLabelDataset(Dataset):
    """Dataset of (screenshot, routing_label) pairs for distillation."""

    def __init__(self, labels_file: str, processor=None):
        self.samples = []
        with open(labels_file) as f:
            for line in f:
                if line.strip():
                    self.samples.append(json.loads(line))

        self.processor = processor
        logger.info(f"Loaded {len(self.samples)} routing labels from {labels_file}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        image_path = sample["image_path"]
        expert_label = sample["expert_label"]
        routing_weights = torch.tensor(sample["routing_weights"], dtype=torch.float32)

        # Load and preprocess image
        from PIL import Image
        try:
            image = Image.open(image_path).convert("RGB")
            if self.processor is not None:
                inputs = self.processor(images=image, return_tensors="pt")
                pixel_values = inputs["pixel_values"].squeeze(0)
            else:
                pixel_values = torch.zeros(3, 224, 224)  # placeholder
        except Exception:
            pixel_values = torch.zeros(3, 224, 224)
            expert_label = 0
            routing_weights = torch.ones(len(routing_weights)) / len(routing_weights)

        return {
            "pixel_values": pixel_values,
            "expert_label": expert_label,
            "routing_weights": routing_weights,
        }


def train(
    labels_file: str,
    output_dir: str,
    vision_model: str = "google/siglip-base-patch16-224",
    num_experts: int = 6,
    epochs: int = 10,
    lr: float = 1e-4,
    batch_size: int = 32,
    kl_weight: float = 0.5,
    freeze_vision: bool = True,
    val_split: float = 0.1,
    device: str = "cuda",
    seed: int = 42,
):
    """Train standalone router via distillation."""
    from verl.models.moe.standalone_router import StandaloneRouter
    from transformers import AutoImageProcessor

    torch.manual_seed(seed)

    # Load processor for image preprocessing
    processor = AutoImageProcessor.from_pretrained(vision_model)

    # Create dataset and split
    full_dataset = RoutingLabelDataset(labels_file, processor=processor)
    val_size = int(len(full_dataset) * val_split)
    train_size = len(full_dataset) - val_size
    train_dataset, val_dataset = torch.utils.data.random_split(
        full_dataset, [train_size, val_size],
        generator=torch.Generator().manual_seed(seed),
    )

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True,
        num_workers=4, pin_memory=True, drop_last=True,
    )
    val_loader = DataLoader(
        val_dataset, batch_size=batch_size, shuffle=False,
        num_workers=4, pin_memory=True,
    )

    logger.info(f"Train: {train_size}, Val: {val_size}")

    # Create standalone router
    router = StandaloneRouter(
        num_experts=num_experts,
        vision_model=vision_model,
        freeze_vision=freeze_vision,
    )
    router._load_vision_encoder()
    router = router.to(device)

    # Optimizer: only train projection + classifier (and optionally vision encoder)
    trainable_params = [
        {"params": router.vision_proj.parameters(), "lr": lr},
        {"params": router.classifier.parameters(), "lr": lr},
    ]
    if not freeze_vision:
        trainable_params.append(
            {"params": router.vision_encoder.parameters(), "lr": lr * 0.1}
        )

    optimizer = torch.optim.AdamW(trainable_params, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    ce_loss_fn = nn.CrossEntropyLoss()

    best_val_acc = 0.0
    os.makedirs(output_dir, exist_ok=True)

    for epoch in range(epochs):
        # === Train ===
        router.train()
        if freeze_vision:
            router.vision_encoder.eval()

        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [train]"):
            pixel_values = batch["pixel_values"].to(device)
            labels = batch["expert_label"].to(device)
            soft_targets = batch["routing_weights"].to(device)

            logits = router(pixel_values)

            # CE loss on hard labels
            ce_loss = ce_loss_fn(logits, labels)

            # KL divergence on soft targets
            log_probs = F.log_softmax(logits, dim=-1)
            kl_loss = F.kl_div(log_probs, soft_targets, reduction='batchmean')

            loss = ce_loss + kl_weight * kl_loss

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(router.parameters(), max_norm=1.0)
            optimizer.step()

            train_loss += loss.item() * pixel_values.size(0)
            preds = logits.argmax(dim=-1)
            train_correct += (preds == labels).sum().item()
            train_total += pixel_values.size(0)

        scheduler.step()

        train_loss /= train_total
        train_acc = train_correct / train_total

        # === Validate ===
        router.eval()
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for batch in tqdm(val_loader, desc=f"Epoch {epoch+1}/{epochs} [val]"):
                pixel_values = batch["pixel_values"].to(device)
                labels = batch["expert_label"].to(device)

                logits = router(pixel_values)
                preds = logits.argmax(dim=-1)
                val_correct += (preds == labels).sum().item()
                val_total += pixel_values.size(0)

        val_acc = val_correct / val_total if val_total > 0 else 0.0

        logger.info(
            f"Epoch {epoch+1}/{epochs}: "
            f"train_loss={train_loss:.4f}, train_acc={train_acc:.4f}, "
            f"val_acc={val_acc:.4f}"
        )

        # Save best model
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            router.save(os.path.join(output_dir, "best"))
            logger.info(f"New best val_acc: {val_acc:.4f}")

    # Save final model
    router.save(os.path.join(output_dir, "final"))
    logger.info(f"Training complete. Best val_acc: {best_val_acc:.4f}")

    # Save training summary
    summary = {
        "best_val_acc": best_val_acc,
        "epochs": epochs,
        "num_experts": num_experts,
        "vision_model": vision_model,
        "train_size": train_size,
        "val_size": val_size,
    }
    with open(os.path.join(output_dir, "training_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)


def main():
    parser = argparse.ArgumentParser(description="Train standalone router via distillation")
    parser.add_argument("--labels", type=str, required=True, help="Path to routing_labels.jsonl")
    parser.add_argument("--output_dir", type=str, default="standalone_router_checkpoint")
    parser.add_argument("--vision_model", type=str, default="google/siglip-base-patch16-224")
    parser.add_argument("--num_experts", type=int, default=6)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--kl_weight", type=float, default=0.5, help="Weight for KL divergence loss")
    parser.add_argument("--freeze_vision", action="store_true", default=True)
    parser.add_argument("--no_freeze_vision", dest="freeze_vision", action="store_false")
    parser.add_argument("--val_split", type=float, default=0.1)
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    train(
        labels_file=args.labels,
        output_dir=args.output_dir,
        vision_model=args.vision_model,
        num_experts=args.num_experts,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
        kl_weight=args.kl_weight,
        freeze_vision=args.freeze_vision,
        val_split=args.val_split,
        device=args.device,
        seed=args.seed,
    )


if __name__ == "__main__":
    main()
